name: BossPlugin
version: '${project.version}'
main: org.attgwrat.bossplugin.BossPlugin
api-version: '1.20'
load: POSTWORLD
commands:
  villagetp:
    description: Teleports to village
    usage: /<command>
